# Generated by Django 4.2.9 on 2024-01-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_remove_tournament_city_tournament_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='locationLat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='locationLon',
            field=models.FloatField(null=True),
        ),
    ]
