# Generated by Django 4.2.9 on 2024-01-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_tournament_locationlat_tournament_locationlon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='locationLat',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='locationLon',
        ),
        migrations.AddField(
            model_name='tournament',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
