# Generated by Django 4.2.9 on 2024-01-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_remove_tournament_location_tournament_locationlat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
